-- =====================================================================
--  Rudra InfoTech Lab — initial content
--  GENERATED by `npm run sql` from src/data/seed.ts — edit that file, not this one.
--  Run after supabase/setup.sql. Safe to re-run: existing rows are left untouched.
-- =====================================================================
begin;
set local ritl.seeding = 'on';  -- keep the activity log clean

insert into public.project_categories (name, display_order) values
  ('E-commerce', 1),
  ('Job portal', 2),
  ('Web development', 3),
  ('Services marketplace', 4),
  ('Business website', 5),
  ('Food & drink', 6)
on conflict (name) do nothing;

insert into public.technologies (name, kind, category, official_url, in_toolkit, display_order) values
  ('HTML5', 'Markup', 'Frontend', 'https://developer.mozilla.org/en-US/docs/Web/HTML', true, 1),
  ('CSS3', 'Styling', 'Frontend', 'https://developer.mozilla.org/en-US/docs/Web/CSS', true, 2),
  ('JavaScript', 'Language', 'Language', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', true, 3),
  ('TypeScript', 'Typed language', 'Language', 'https://www.typescriptlang.org', true, 4),
  ('Angular', 'Framework', 'Frontend', 'https://angular.dev', true, 5),
  ('React', 'UI library', 'Frontend', 'https://react.dev', true, 6),
  ('Next.js', 'React framework', 'Frontend', 'https://nextjs.org', true, 7),
  ('Node.js', 'Runtime', 'Backend', 'https://nodejs.org', true, 8),
  ('Tailwind CSS', 'Utility CSS', 'Frontend', 'https://tailwindcss.com', true, 9),
  ('Git', 'Version control', 'Tooling', 'https://git-scm.com', true, 10),
  ('REST APIs', 'Integration', 'Backend', null, true, 11),
  ('TanStack Start', 'React framework', 'Frontend', 'https://tanstack.com/start', false, 12),
  ('Supabase', 'Backend platform', 'Backend', 'https://supabase.com', false, 13),
  ('Razorpay', 'Payments', 'Payments', 'https://razorpay.com', false, 14)
on conflict (name) do nothing;

insert into public.projects (slug, name, short_description, full_description, project_type, category_id, platform, client_name, live_url, app_url, play_store_url, github_url, completion_year, project_logo, featured_image, desktop_screenshot, mobile_screenshot, accent, headline, image_alt, app_category, status, featured, display_order, seo_title, seo_description, social_image, canonical_url)
values ('dotaanke-store', 'Dotaanke.store', 'An online store for hand-embroidered Indian shirts and kurtis — shop, product pages, wishlist, checkout and order tracking.', 'Dotaanke sells hand-embroidered Indian shirts and kurtis. The store covers the full path from browsing to delivery: a shop with product pages, a wishlist, checkout and order tracking.', 'E-COMMERCE', (select id from public.project_categories where name = 'E-commerce'), 'web', null, 'https://dotaanke.store', null, null, null, null, null, '/work/dotaanke-store-hero.webp', null, null, '#e56d7a', 'Every stitch tells a story.', 'Gold hand embroidery on ivory fabric — hero image from the Dotaanke.store homepage', null, 'published', true, 1, null, null, null, null)
on conflict (slug) do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 1 from public.projects p, public.technologies t where p.slug = 'dotaanke-store' and t.name = 'React'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 2 from public.projects p, public.technologies t where p.slug = 'dotaanke-store' and t.name = 'TanStack Start'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 3 from public.projects p, public.technologies t where p.slug = 'dotaanke-store' and t.name = 'Tailwind CSS'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 4 from public.projects p, public.technologies t where p.slug = 'dotaanke-store' and t.name = 'Supabase'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 5 from public.projects p, public.technologies t where p.slug = 'dotaanke-store' and t.name = 'Razorpay'
on conflict do nothing;

insert into public.projects (slug, name, short_description, full_description, project_type, category_id, platform, client_name, live_url, app_url, play_store_url, github_url, completion_year, project_logo, featured_image, desktop_screenshot, mobile_screenshot, accent, headline, image_alt, app_category, status, featured, display_order, seo_title, seo_description, social_image, canonical_url)
values ('rojgarlelo-site', 'RojgarLelo.site', 'Recruitment listings for job seekers across India — searchable openings, detailed job pages and an admin area for publishing new roles.', 'RojgarLelo lists job openings for job seekers across India. Visitors can search openings and read detailed job pages; the team publishes new roles from an admin area.', 'WEB APPLICATION', (select id from public.project_categories where name = 'Job portal'), 'web', null, 'https://rojgarlelo.site', null, null, null, null, null, null, null, null, '#1779e1', 'Find a job that fits your life', null, null, 'published', true, 2, null, null, null, null)
on conflict (slug) do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 1 from public.projects p, public.technologies t where p.slug = 'rojgarlelo-site' and t.name = 'React'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 2 from public.projects p, public.technologies t where p.slug = 'rojgarlelo-site' and t.name = 'TanStack Start'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 3 from public.projects p, public.technologies t where p.slug = 'rojgarlelo-site' and t.name = 'Tailwind CSS'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 4 from public.projects p, public.technologies t where p.slug = 'rojgarlelo-site' and t.name = 'Supabase'
on conflict do nothing;

insert into public.projects (slug, name, short_description, full_description, project_type, category_id, platform, client_name, live_url, app_url, play_store_url, github_url, completion_year, project_logo, featured_image, desktop_screenshot, mobile_screenshot, accent, headline, image_alt, app_category, status, featured, display_order, seo_title, seo_description, social_image, canonical_url)
values ('mightymindz-in', 'MightyMindz.in', 'A live website designed and built by the lab. Visit the site to see it in action.', null, null, (select id from public.project_categories where name = 'Web development'), 'web', null, 'https://mightymindz.in', null, null, null, null, null, null, null, null, '#dfff36', null, null, null, 'published', true, 3, null, null, null, null)
on conflict (slug) do nothing;

insert into public.projects (slug, name, short_description, full_description, project_type, category_id, platform, client_name, live_url, app_url, play_store_url, github_url, completion_year, project_logo, featured_image, desktop_screenshot, mobile_screenshot, accent, headline, image_alt, app_category, status, featured, display_order, seo_title, seo_description, social_image, canonical_url)
values ('sarkar2-0-pw', 'Sarkar2-0.pw', 'Connects people across Uttar Pradesh with verified electricians, plumbers, painters and mechanics — plus an electrical & electronics store, in Hindi and English.', 'Sarkar2.0 connects people across Uttar Pradesh with verified electricians, plumbers, painters and mechanics. It also runs an electrical and electronics store.

The whole platform works in Hindi and English.', 'WEB APPLICATION', (select id from public.project_categories where name = 'Services marketplace'), 'web', null, 'https://sarkar2-0.pw', null, null, null, null, null, '/work/sarkar2-0-pw-hero.webp', null, null, '#f52027', 'Every mistri, one platform.', 'Skilled workers in hard hats — hero image from the Sarkar2.0 homepage', null, 'published', true, 4, null, null, null, null)
on conflict (slug) do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 1 from public.projects p, public.technologies t where p.slug = 'sarkar2-0-pw' and t.name = 'React'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 2 from public.projects p, public.technologies t where p.slug = 'sarkar2-0-pw' and t.name = 'TanStack Start'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 3 from public.projects p, public.technologies t where p.slug = 'sarkar2-0-pw' and t.name = 'Tailwind CSS'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 4 from public.projects p, public.technologies t where p.slug = 'sarkar2-0-pw' and t.name = 'Supabase'
on conflict do nothing;

insert into public.projects (slug, name, short_description, full_description, project_type, category_id, platform, client_name, live_url, app_url, play_store_url, github_url, completion_year, project_logo, featured_image, desktop_screenshot, mobile_screenshot, accent, headline, image_alt, app_category, status, featured, display_order, seo_title, seo_description, social_image, canonical_url)
values ('rahulconstructionwork-site', 'RahulConstructionWork.site', 'The website of a Haridwar construction and interiors firm — services, project portfolio, the build process and a quote request form.', 'The website of a construction and interiors firm in Haridwar. It presents the firm''s services, a portfolio of completed projects and its build process, and collects quote requests through a form.', 'BUSINESS WEBSITE', (select id from public.project_categories where name = 'Business website'), 'web', null, 'https://rahulconstructionwork.site', null, null, null, null, null, '/work/rahulconstructionwork-site-hero.webp', null, null, '#ddb049', 'Building Dreams, Designing Excellence', 'A modern villa lit at dusk beside a pool — from the Rahul Construction Works portfolio', null, 'published', true, 5, null, null, null, null)
on conflict (slug) do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 1 from public.projects p, public.technologies t where p.slug = 'rahulconstructionwork-site' and t.name = 'React'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 2 from public.projects p, public.technologies t where p.slug = 'rahulconstructionwork-site' and t.name = 'TanStack Start'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 3 from public.projects p, public.technologies t where p.slug = 'rahulconstructionwork-site' and t.name = 'Tailwind CSS'
on conflict do nothing;
insert into public.project_technologies (project_id, technology_id, display_order)
  select p.id, t.id, 4 from public.projects p, public.technologies t where p.slug = 'rahulconstructionwork-site' and t.name = 'Supabase'
on conflict do nothing;

insert into public.projects (slug, name, short_description, full_description, project_type, category_id, platform, client_name, live_url, app_url, play_store_url, github_url, completion_year, project_logo, featured_image, desktop_screenshot, mobile_screenshot, accent, headline, image_alt, app_category, status, featured, display_order, seo_title, seo_description, social_image, canonical_url)
values ('the-lord-cafe', 'THE LORD CAFE', 'The Android app of THE LORD CAFE, a wood-fired pizza brand — live on Google Play.', 'THE LORD CAFE is a wood-fired pizza brand. Its Android app is published on Google Play.

The imagery here is the brand''s own photography and logo.', 'ANDROID APPLICATION', (select id from public.project_categories where name = 'Food & drink'), 'android', 'THE LORD CAFE', null, null, 'https://play.google.com/store/apps/details?id=com.thelordcafe.pizza&pli=1', null, null, '/work/the-lord-cafe-icon.png', '/work/the-lord-cafe-hero.webp', null, null, '#f0f0d8', 'Wood-Fired Pizza Delivered in 30 Minutes', 'A wood-fired margherita pizza on a wooden peel — brand photography from THE LORD CAFE', null, 'published', true, 6, null, null, null, null)
on conflict (slug) do nothing;
insert into public.project_images (project_id, url, kind, alt, display_order)
  select p.id, '/work/the-lord-cafe-margherita-phone.webp', 'gallery', 'Wood-fired margherita pizza — brand photography from THE LORD CAFE', 1 from public.projects p
  where p.slug = 'the-lord-cafe' and not exists (select 1 from public.project_images i where i.project_id = p.id and i.url = '/work/the-lord-cafe-margherita-phone.webp');
insert into public.project_images (project_id, url, kind, alt, display_order)
  select p.id, '/work/the-lord-cafe-pepperoni-phone.webp', 'gallery', 'Pepperoni pizza — brand photography from THE LORD CAFE', 2 from public.projects p
  where p.slug = 'the-lord-cafe' and not exists (select 1 from public.project_images i where i.project_id = p.id and i.url = '/work/the-lord-cafe-pepperoni-phone.webp');
insert into public.project_images (project_id, url, kind, alt, display_order)
  select p.id, '/work/the-lord-cafe-burger-phone.webp', 'gallery', 'A burger — brand photography from THE LORD CAFE', 3 from public.projects p
  where p.slug = 'the-lord-cafe' and not exists (select 1 from public.project_images i where i.project_id = p.id and i.url = '/work/the-lord-cafe-burger-phone.webp');

insert into public.services (slug, title, display, short_description, full_description, points, symbol, published, display_order, seo_title, seo_description) values
  ('website-design', 'Website Design', 'Website|Design', 'Interfaces shaped around your business.', 'Modern UI/UX and visual systems designed around your brand, your audience and the one action you need visitors to take.

We start from how your customers decide, then shape the layout, typography and visual direction around that decision — so the site looks like you and works for you.', array['UI / UX design', 'Visual direction', 'Design systems']::text[], 'design', true, 1, null, null),
  ('web-development', 'Web Development', 'Web|Development', 'Production-ready, from the first commit.', 'Responsive, scalable websites built with clean, maintainable code — engineered to load fast and hold up as you grow.

From static marketing sites to custom web applications with logins, dashboards and databases, we build what the project needs and nothing it doesn''t.', array['Responsive builds', 'Clean code', 'Deployment']::text[], 'development', true, 2, null, null),
  ('business-websites', 'Business Websites', 'Business|Websites', 'Credibility, on every screen.', 'Professional websites that tell your story clearly, earn trust in seconds and turn visitors into enquiries.

Services, portfolio, contact and quote forms — structured so a visitor always knows what you do and how to reach you.', array['Clear messaging', 'Enquiry flows', 'Local presence']::text[], 'business', true, 3, null, null),
  ('ecommerce-development', 'E-commerce Development', 'E-commerce|Development', 'Storefronts built to sell.', 'Modern online stores designed around your products — clean browsing, confident checkout, fewer abandoned carts.

Product catalogues, wishlists, payments and order tracking, designed mobile-first because that''s where your customers shop.', array['Product catalogues', 'Checkout UX', 'Mobile-first']::text[], 'ecommerce', true, 4, null, null),
  ('landing-pages', 'Landing Pages', 'Landing|Pages', 'One page. One job. Done well.', 'Focused pages for launches, campaigns, products and lead generation — built to convert, measured to improve.

One message, one action, no distractions.', array['Campaign pages', 'Lead capture', 'A/B-ready']::text[], 'landing', true, 5, null, null),
  ('website-redesign', 'Website Redesign', 'Website|Redesign', 'Old site, new standard.', 'We take outdated websites and rebuild them into modern experiences — keeping what works, fixing what doesn''t.

We review what your current site does well, then rebuild the rest with a modern design and a faster, cleaner codebase.', array['UX audit', 'Visual refresh', 'Rebuild']::text[], 'redesign', true, 6, null, null),
  ('android-apps', 'Android Apps', 'Android|Apps', 'Your business, in your customer''s pocket.', 'Android apps for businesses that want to be one tap away — designed around your brand and published on Google Play.

We can build the app alongside your website so both tell the same story.', array['Android apps', 'Google Play release', 'Brand-first UI']::text[], 'android', true, 7, null, null),
  ('performance-optimization', 'Performance Optimization', 'Performance|Optimization', 'Every millisecond counts.', 'We tune speed, responsiveness and Core Web Vitals so your site feels instant — for users and for search engines.

Images, fonts, scripts and hosting: we find what slows your pages down and fix it.', array['Core Web Vitals', 'Asset optimisation', 'Technical SEO']::text[], 'performance', true, 8, null, null),
  ('maintenance-support', 'Maintenance & Support', 'Maintenance|& Support', 'We don''t disappear after launch.', 'Ongoing updates, fixes, improvements and technical support — so your website keeps working as hard as you do.

Content updates, new sections, fixes and technical help when you need it.', array['Updates & fixes', 'Improvements', 'Technical support']::text[], 'support', true, 9, null, null)
on conflict (slug) do nothing;

insert into public.process_steps (name, description, published, display_order)
select * from (values
  ('Discover', 'We learn your business, audience, objectives and requirements — before a single pixel is placed.', true, 1),
  ('Design', 'We establish the visual direction and user experience, and refine it with you until it''s right.', true, 2),
  ('Develop', 'We turn the approved design into a fast, responsive, production-ready website.', true, 3),
  ('Test', 'We check responsiveness, usability, functionality and performance across devices and browsers.', true, 4),
  ('Launch', 'We prepare, configure and deploy the production website — then watch it go live.', true, 5),
  ('Improve', 'We keep refining the site when you need it: new features, updates and optimisations.', true, 6)
) as v (name, description, published, display_order)
where not exists (select 1 from public.process_steps);

insert into public.content_sections (key, data) values
  ('hero', '{"meta_1":"/ Digital foundry","meta_2":"India / Worldwide","serif":"Impossible to ignore.","heading":"We build websites that make businesses impossible to ignore.","description":"Modern, fast, responsive digital experiences — designed and developed for businesses, brands, startups and entrepreneurs.","primary_cta":"Start a project","secondary_cta":"View our work"}'::jsonb),
  ('philosophy', '{"lead":"Your website isn''t just a page on the internet. It''s","statement_1":"Your digital","statement_2":"first impression.","description":"Visitors decide in seconds whether to trust you. We make those seconds count — by treating design, development, performance and usability as one discipline, not four separate jobs.","design":"Interfaces with a point of view — clear, considered, unmistakably yours.","develop":"Clean, responsive builds that behave on every screen size.","perform":"Lightweight pages that load fast and stay fast.","convert":"Obvious paths to the one thing you want visitors to do."}'::jsonb),
  ('work', '{"description":"Real projects on real domains. Don''t take our word for it — click through and judge for yourself."}'::jsonb),
  ('apps', '{"description":"Not just websites. We build Android apps too — designed around the brand and published on Google Play."}'::jsonb),
  ('services', '{"heading":"Everything your website needs.","highlight":"Nothing it doesn''t.","description":"From the first sketch to ongoing support — one lab, one standard, end to end."}'::jsonb),
  ('about', '{"statement_1":"A small lab","statement_2":"with a serious standard.","paragraphs":"Rudra InfoTech Lab is a web design and development studio. We build websites for businesses, brands, startups and entrepreneurs who want more from the web than a page that simply exists.\n\nWe work like a lab: curious, hands-on and a little obsessive about the details. You talk directly to the people designing your pages and writing your code — so ideas don''t get lost in translation.\n\nSmall enough to care about your project personally. Technical enough to build it properly.","what_we_do":"Website design & development","who_its_for":"Businesses, brands, startups & entrepreneurs","how_we_work":"Directly, transparently, end to end"}'::jsonb),
  ('contact', '{"heading_1":"Have","heading_2":"an idea?","serif":"Let''s build it.","description":"A few details are all we need. We''ll read every word, then reply with honest next steps — no jargon, no pressure.","button":"Send the brief","whatsapp_cta":"Chat on WhatsApp","success_title":"Brief received.","success_text":"Thanks — your project is in the lab. We''ll get back to you shortly with next steps."}'::jsonb),
  ('footer', '{"statement":"Make something worth visiting.","tagline":"Web design & development studio"}'::jsonb)
on conflict (key) do nothing;

insert into public.site_settings (key, value, is_public) values
  ('contact', '{"email":"","phone":"","whatsapp":"351930656040","whatsapp_message":"Hi Rudra InfoTech Lab, I’m interested in discussing a website/app project.","instagram":"","linkedin":"","github":"","location":"","availability":"available","default_country_code":"91"}'::jsonb, true),
  ('form', '{"services":["Website Design","Web Development","E-commerce","Landing Page","Website Redesign","Web Application","Android Application","Custom Development"],"budgets":["Under ₹25k","₹25k – ₹75k","₹75k – ₹2L","₹2L +","Not sure yet"]}'::jsonb, true),
  ('publish', '{}'::jsonb, false)
on conflict (key) do nothing;

insert into public.seo_settings (id, site_title, meta_description, canonical_base_url, og_title, og_description, og_image, twitter_image, favicon, app_icon, robots_index)
values (1, 'Rudra InfoTech Lab — Web Design & Development Agency', 'Web development agency building fast, responsive, business-focused websites and Android apps: business sites, e-commerce, landing pages, redesigns and custom builds.', '', 'Rudra InfoTech Lab — Websites & apps that make businesses impossible to ignore', 'A web design and development lab building fast, responsive websites and Android apps for businesses, brands, startups and entrepreneurs.', '/og-v3.png', '/og-v3.png', '', '', true)
on conflict (id) do nothing;

commit;
