/**
 * Writes supabase/seed.sql from src/data/seed.ts so a fresh database starts with
 * exactly the content the site shows today.   npm run sql
 * The file is idempotent: re-running it never duplicates or overwrites rows.
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { ROOT } from "./paths.js";
import { seed } from "../src/data/seed.js";

const q = (v: string | null | undefined): string => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const b = (v: boolean): string => (v ? "true" : "false");
const n = (v: number | null | undefined): string => (v === null || v === undefined ? "null" : String(Number(v)));
const arr = (a: string[]): string => (a.length ? `array[${a.map(q).join(", ")}]::text[]` : "'{}'::text[]");
const j = (o: unknown): string => `${q(JSON.stringify(o))}::jsonb`;

async function main() {
  const d = seed();
  const out: string[] = [];
  const w = (s: string) => out.push(s);

  w(`-- =====================================================================`);
  w(`--  Rudra InfoTech Lab — initial content`);
  w(`--  GENERATED by \`npm run sql\` from src/data/seed.ts — edit that file, not this one.`);
  w(`--  Run after supabase/setup.sql. Safe to re-run: existing rows are left untouched.`);
  w(`-- =====================================================================`);
  w(`begin;`);
  w(`set local ritl.seeding = 'on';  -- keep the activity log clean`);
  w(``);

  w(`insert into public.project_categories (name, display_order) values`);
  w(d.categories.map((c, i) => `  (${q(c)}, ${i + 1})`).join(",\n") + `\non conflict (name) do nothing;\n`);

  w(`insert into public.technologies (name, kind, category, official_url, in_toolkit, display_order) values`);
  w(d.tech.map((t) => `  (${q(t.name)}, ${q(t.kind)}, ${q(t.category)}, ${q(t.official_url ?? null)}, ${b(t.in_toolkit)}, ${n(t.display_order)})`).join(",\n") + `\non conflict (name) do nothing;\n`);

  for (const p of d.projects) {
    w(`insert into public.projects (slug, name, short_description, full_description, project_type, category_id, platform, client_name, live_url, app_url, play_store_url, github_url, completion_year, project_logo, featured_image, desktop_screenshot, mobile_screenshot, accent, headline, image_alt, app_category, status, featured, display_order, seo_title, seo_description, social_image, canonical_url)`);
    w(
      `values (${[
        q(p.slug), q(p.name), q(p.short_description), q(p.full_description ?? null), q(p.project_type ?? null),
        p.category ? `(select id from public.project_categories where name = ${q(p.category)})` : "null",
        q(p.platform), q(p.client_name ?? null), q(p.live_url ?? null), q(p.app_url ?? null), q(p.play_store_url ?? null), q(p.github_url ?? null),
        n(p.completion_year ?? null), q(p.project_logo ?? null), q(p.featured_image ?? null), q(p.desktop_screenshot ?? null), q(p.mobile_screenshot ?? null),
        q(p.accent ?? null), q(p.headline ?? null), q(p.image_alt ?? null), q(p.app_category ?? null), q(p.status), b(p.featured), n(p.display_order),
        q(p.seo_title ?? null), q(p.seo_description ?? null), q(p.social_image ?? null), q(p.canonical_url ?? null),
      ].join(", ")})\non conflict (slug) do nothing;`
    );
    p.technologies.forEach((t, i) =>
      w(`insert into public.project_technologies (project_id, technology_id, display_order)\n  select p.id, t.id, ${i + 1} from public.projects p, public.technologies t where p.slug = ${q(p.slug)} and t.name = ${q(t)}\non conflict do nothing;`)
    );
    for (const im of p.images) {
      w(
        `insert into public.project_images (project_id, url, kind, alt, display_order)\n  select p.id, ${q(im.url)}, ${q(im.kind)}, ${q(im.alt ?? null)}, ${n(im.display_order)} from public.projects p\n  where p.slug = ${q(p.slug)} and not exists (select 1 from public.project_images i where i.project_id = p.id and i.url = ${q(im.url)});`
      );
    }
    w(``);
  }

  w(`insert into public.services (slug, title, display, short_description, full_description, points, symbol, published, display_order, seo_title, seo_description) values`);
  w(
    d.services
      .map((s) => `  (${[q(s.slug), q(s.title), q(s.display), q(s.short_description), q(s.full_description), arr(s.points), q(s.symbol), b(s.published), n(s.display_order), q(s.seo_title ?? null), q(s.seo_description ?? null)].join(", ")})`)
      .join(",\n") + `\non conflict (slug) do nothing;\n`
  );

  w(`insert into public.process_steps (name, description, published, display_order)`);
  w(`select * from (values\n${d.process.map((s) => `  (${q(s.name)}, ${q(s.description)}, ${b(s.published)}, ${n(s.display_order)})`).join(",\n")}\n) as v (name, description, published, display_order)`);
  w(`where not exists (select 1 from public.process_steps);\n`);

  w(`insert into public.content_sections (key, data) values`);
  w((Object.keys(d.content) as (keyof typeof d.content)[]).map((k) => `  (${q(k)}, ${j(d.content[k])})`).join(",\n") + `\non conflict (key) do nothing;\n`);

  w(`insert into public.site_settings (key, value, is_public) values`);
  w(`  ('contact', ${j(d.contact)}, true),\n  ('form', ${j(d.form)}, true),\n  ('publish', '{}'::jsonb, false)\non conflict (key) do nothing;\n`);

  const s = d.seo;
  w(`insert into public.seo_settings (id, site_title, meta_description, canonical_base_url, og_title, og_description, og_image, twitter_image, favicon, app_icon, robots_index)`);
  w(`values (1, ${[q(s.site_title), q(s.meta_description), q(s.canonical_base_url), q(s.og_title), q(s.og_description), q(s.og_image), q(s.twitter_image), q(s.favicon), q(s.app_icon), b(s.robots_index)].join(", ")})\non conflict (id) do nothing;\n`);

  w(`commit;`);
  const file = join(ROOT, "supabase/seed.sql");
  await writeFile(file, out.join("\n") + "\n");
  console.log(`  ✓ supabase/seed.sql (${d.projects.length} projects, ${d.services.length} services, ${d.tech.length} technologies)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
